import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { useState } from "react";
import { AppHeader } from "@/components/AppHeader";
import { SeverityTag, StatusBadge } from "@/components/bits";
import { SEVERITIES, SEVERITY_HEX, datasetQuery, fmtDate } from "@/lib/monitoring";

export const Route = createFileRoute("/alerts")({
  loader: ({ context }) => context.queryClient.ensureQueryData(datasetQuery),
  head: () => ({
    meta: [
      { title: "Alert Center — SolarScope Armenia" },
      { name: "description", content: "Active and resolved monitoring alerts for Armenian solar stations: critical condition, deterioration, anomalies and data failures." },
      { property: "og:title", content: "Alert Center — SolarScope Armenia" },
      { property: "og:description", content: "Which solar stations triggered alerts, why, and what to do next." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: AlertsPage,
});

const RULE_LABEL: Record<string, string> = {
  critical_condition: "Critical condition",
  significant_deterioration: "Significant deterioration",
  critical_anomaly: "Critical anomaly",
  multiple_problems: "Multiple problems",
  data_failure: "Data failure",
};

function AlertsPage() {
  const { data } = useSuspenseQuery(datasetQuery);
  const [status, setStatus] = useState<"active" | "resolved" | "all">("active");
  const [sev, setSev] = useState<string | null>(null);
  const list = data.alerts.filter((a) => (status === "all" || a.status === status) && (!sev || a.severity === sev));
  const counts = Object.fromEntries(SEVERITIES.map((s) => [s, data.alerts.filter((a) => a.status === "active" && a.severity === s).length]));
  const chip = (on: boolean) => `px-2.5 py-1 text-[12px] border ${on ? "border-solar/60 bg-solar/10 text-solar" : "border-line text-dim hover:text-ink"}`;

  return (
    <div className="min-h-screen bg-base">
      <AppHeader />
      <main className="mx-auto max-w-5xl p-4">
        <h1 className="text-[26px] font-bold uppercase">Alert center</h1>
        <p className="text-dim">Alerts are generated by deterministic rules on monitoring data — they indicate where to look, not confirmed faults.</p>
        <div className="mt-4 grid grid-cols-4 gap-px bg-line">
          {SEVERITIES.map((s) => (
            <button key={s} onClick={() => setSev(sev === s ? null : s)} className={`bg-surface p-3 text-left hover:bg-raised ${sev === s ? "!bg-raised" : ""}`}>
              <p className="font-mono text-[24px] font-semibold" style={{ color: SEVERITY_HEX[s] }}>{counts[s]}</p>
              <p className="label-caps capitalize">{s} · active</p>
            </button>
          ))}
        </div>
        <div className="mt-4 flex gap-1">
          {(["active", "resolved", "all"] as const).map((s) => <button key={s} onClick={() => setStatus(s)} className={`${chip(status === s)} capitalize`}>{s}</button>)}
        </div>
        <ul className="mt-3 space-y-2">
          {list.map((a) => (
            <li key={a.id} className={`border border-line bg-surface ${a.status === "resolved" ? "opacity-60" : ""}`} style={{ boxShadow: `inset 3px 0 0 ${SEVERITY_HEX[a.severity]}` }}>
              <div className="flex flex-wrap items-start justify-between gap-3 p-3">
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <SeverityTag severity={a.severity} />
                    <span className="label-caps">{RULE_LABEL[a.rule] ?? a.rule}</span>
                    <span className="text-[11px] text-dim">· {fmtDate(a.created_at)} · {a.status}</span>
                  </div>
                  <p className="mt-1 text-[14px] font-semibold">{a.station.name} — {a.title}</p>
                  <p className="text-[12px]">{a.message}</p>
                  {a.condition_from != null && a.condition_to != null && (
                    <p className="mt-1 font-mono text-[12px] text-dim">Condition {a.condition_from} → <span className="text-critical">{a.condition_to}</span></p>
                  )}
                  <p className="mt-1 text-[12px] text-solar">→ {a.action}</p>
                </div>
                <div className="flex flex-col items-end gap-2">
                  <StatusBadge status={a.station.status} />
                  <Link to="/" search={{ station: a.station_id }} className="border border-line px-2.5 py-1 text-[12px] hover:border-solar/60 hover:text-solar">View on map →</Link>
                </div>
              </div>
            </li>
          ))}
          {list.length === 0 && <li className="border border-line bg-surface p-6 text-center text-dim">No alerts in this view.</li>}
        </ul>
      </main>
    </div>
  );
}
